### ISSUE TITLE
getIRQ and clearIRQ functions.

### ISSUE THREAD

**Issue by C47D** [C47D/nRF24_Component#2]
When using the getIRQ and clearIRQ functions inside the IRQ interrupt handler doesn't work as expected, when reading the status register it's read as 0x00 and not the correct value (0x1E which is the MAX_RT_IRQ flag for example).
There must be a way to improve both of those functions.

**Comment by C47D** [comment]
Fixed f299728

On the NOPcmd function after sending the NRF_NOP_CMD the function waited for the SPI_STS_SPI_IDLE status like so:
` while (!(SPI_ReadTxStatus() & SPI_STS_SPI_IDLE)) {}`
changing that line for:
`while (!(SPI_ReadTxStatus() & SPI_STS_BYTE_COMPLETE)){}`
solved the error, SPI_STS_BYTE_COMPLETE signal gets asserted after one byte/word is transferred via SPI.

**Comment by mazcoder** [comment]
Hi Carlos. 
I just found this git and am really excited to try it out! I have a project that incorporates several arduino boards and raspberry pi to measure torque data from 4 wireless nodes.

I just ordered a few 059 boards and am a complete new when it comes to psoc. From my discussion [here](https://community.cypress.com/message/143217?et=watches.email.thread#143217)
 I know what I am trying to achieve is possible but maybe not so easily implemented.  Your component will be a huge help for sure!

What kind of data throughput are you getting currently?  
-Josh

**Comment by C47D** [comment]
Hi @mazcoder,

The nRF24 radios can be configured to send data at 250kbps, 1Mbps and 2Mbps. Currently the component is broken, i will work on the week and try to make it work again.

If you have any problem open a new issue and i will try to help you to get familiar with PSoCs and the component.

Regards
@C47D

**Comment by mazcoder** [comment]
Yes I know the data rates available for the nrf24 but from my experience
the data rate and the actual throughput are completely different.

I personally have only ever gotten 100 kHz out of these radios using
arduino and raspberry pi libraries and hardware.

 So i was wondering for example how long would it take to transfer 32 bytes
with your component?

I am looking forward to learning psoc and getting to know your component. I
have used the nrf24 chip a bunch but only with arduino and raspberry pi.

Thanks C47D!


On Oct 1, 2017 12:41 PM, "Carlos Diaz" <notifications@github.com> wrote:

Hi @mazcoder <https://github.com/mazcoder>,

The nRF24 radios can be configured to send data at 250kbps, 1Mbps and
2Mbps. Currently the component is broken, i will work on the week and try
to make it work again.

If you have any problem open a new issue and i will try to help you to get
familiar with PSoCs and the component.

Regards
@C47D <https://github.com/c47d>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/C47D/nRF24_Component/issues/2#issuecomment-333389272>,
or mute the thread

**Comment by C47D** [comment]
Hi @mazcoder :

>  So i was wondering for example how long would it take to transfer 32 bytes with your component?

It depends on the SPI rate, on the image i'm setting the address of the radio (Command (1byte) + Address(5bytes)):

![nrf24_address](https://user-images.githubusercontent.com/11037705/32083105-e61eb882-ba85-11e7-8a81-5c9e46107f27.png)

and it takes 71uS with the SPI @ 1MHz.

Check the [nRF24 Example Projects](github.com/C47D/NRF24_Example_Projects) repo, i'm working on adding more examples using this component.
